### ISSUE TITLE
Regression tests

### ISSUE THREAD

**Issue by merzlab** [merzlab/QUICK#1]
Prepare a suitable set of test cases and include into QUICK. Also write a script that would automatically run this set of tests. A user may run this script to verify the correctness of a QUICK installation.

**Comment by miaoyipu** [comment]
Hi, Madu,

Software development call this continuous integration (CI) in case you don't know. For github, there are a few CI tools, https://github.com/marketplace/category/continuous-integration . I heard Travis-CI(https://github.com/marketplace/travis-ci) is good, and free for open source, that is the least effort way to enable CI.

Another options are GitLab: here is a brief introduction of gitlab (https://about.gitlab.com/), you can use it on cloud or install it on lab-owned machines (https://about.gitlab.com/install/) . I would suggest to ask if iCER has it installed on their services or maybe ask for it if they don't, and you can test on-demand on GPU-enabled iCER machine in that case, most other public cloud services are quite pricy on GPU machine. The free tier is good enough for this project.

**Comment by Madu86** [comment]
Hi Yipu, 

Thank you for your suggestion. I will look at these CI tools. 

With regards,
Madu

**Comment by Madu86** [comment]
Hi Yipu,

I am trying to compile and test QUICK with TravisCI. But it looks like TravisCI is not supporting Fortran 90 (https://docs.travis-ci.com/user/languages/). Have you tasted any fortran codes using this software before?
