### ISSUE TITLE
def2-SV(P) basis set is missing

### ISSUE THREAD

**Issue by agoetz** [merzlab/QUICK#121]
Someone please add the def2-SV(P) basis set. Available on https://www.basissetexchange.org

As an FYI, basis set equivalents are approximately
6-31G* = def2-SV(P)
6-31G** = def2-SVP
6-31G++G(d,p) = def2-SVPD

Only that def2 basis sets are much better (closer to basis set limit for same size).

**Comment by Altaimorin** [comment]
Hi. What format should I pick for the basis set? Is that just GAUSSIAN?

**Comment by Madu86** [comment]
@Altaimorin Yes, but please check after adding it.

**Comment by Altaimorin** [comment]
I see. I have to remove all lines after the ending `****` of `Rn`.

**Comment by Madu86** [comment]
Yes.

**Comment by Altaimorin** [comment]
I added def2-SV(P) basis set.
