### ISSUE TITLE
Store SAD guess for some elements

### ISSUE THREAD

**Issue by Madu86** [merzlab/QUICK#123]
@Altaimorin Some elements are taking a long time for sad guess.  For example, see the following MgCl2 HF/6-31G calculation. The guess takes >90% of time which is totally stupid.

```
------------- TIMING ---------------
| INITIAL GUESS TIME  =   433.190231000( 96.31%)
| TOTAL SCF TIME      =    16.569304000(  3.68%)
|       TOTAL OP TIME      =    16.551735000(  3.68%)
|             TOTAL 1e TIME      =     0.016103000(  0.00%)
|             TOTAL 2e TIME      =    16.519298000(  3.67%)
|       TOTAL DII TIME      =     0.017246000(  0.00%)
|             TOTAL DIAG TIME    =     0.005770000(  0.00%)
| TOTAL TIME          =   449.782826000
------------------------------------ 
```
Please save the atomic density into files and save them into basis folder. QUICK should read them during the guess.

**Comment by Madu86** [comment]
Someone has done this for Zn in past: https://github.com/merzlab/QUICK/blob/master/src/getMolSad.f90#L153-L170

**Comment by Madu86** [comment]
@Altaimorin Lets start with CaCl2 6-31G, 6-31G* and 6-31g**. We need to make sure that basis elements are working. Here is my input. 

```
HF  BASIS=6-31G* cutoff=1.0e-9 denserms=1.0e-6  zmake ENERGY DIPOLE CHARGE=0

Ca        -2.34894        0.18924       -0.07555
Cl        -1.24894        0.18924       -0.07555
Cl        -3.44894        0.18924       -0.07555
```

**Comment by Madu86** [comment]
We should also store guess for F and Br.

**Comment by Altaimorin** [comment]
Where did you get `6-31G2DF2PD.BAS`? It's not in https://www.basissetexchange.org/. There's `6-31G(3df,3pd)` which has fewer atoms in it.

**Comment by Madu86** [comment]
@Altaimorin Comes from Yipu. You can find them here: https://github.com/merzlab/QUICK/tree/QUICK-2.1.0.0/basis

**Comment by Altaimorin** [comment]
@Madu86 Thank you. I would simply keep it in the `basis` folder.

**Comment by Altaimorin** [comment]
> @Altaimorin Lets start with CaCl2 6-31G, 6-31G* and 6-31g**. We need to make sure at least the basic elements are working. Here is my input.
> 
> ```
> HF  BASIS=6-31G* cutoff=1.0e-9 denserms=1.0e-6  zmake ENERGY DIPOLE CHARGE=0
> 
> Ca        -2.34894        0.18924       -0.07555
> Cl        -1.24894        0.18924       -0.07555
> Cl        -3.44894        0.18924       -0.07555
> ```

Yes there's a problem with CaCls after SAD guess when calling DGEMM. Working on this now.

**Comment by Altaimorin** [comment]
> > @Altaimorin Lets start with CaCl2 6-31G, 6-31G* and 6-31g**. We need to make sure at least the basic elements are working. Here is my input.
> > ```
> > HF  BASIS=6-31G* cutoff=1.0e-9 denserms=1.0e-6  zmake ENERGY DIPOLE CHARGE=0
> > 
> > Ca        -2.34894        0.18924       -0.07555
> > Cl        -1.24894        0.18924       -0.07555
> > Cl        -3.44894        0.18924       -0.07555
> > ```
> 
> Yes there's a problem with CaCl2 after SAD guess when calling DGEMM. Working on this now.

I think you have fixed this in by adding `call upcase(keywd,80)` in `quick_molspec_module.f90` so that it allows the element names to have lower case letters.
