### ISSUE TITLE
Check basis set files for supported elements

### ISSUE THREAD

**Issue by agoetz** [merzlab/QUICK#141]
We have Iodine in the def2-SV(P) and def2-SVP basis sets. These have to be used with the corresponding 28-electron def2-ECPs. We do have ECP routines but I am not sure if those work. I have not tested. I also do not see ECP info in the basis set files. If we don't support ECPs, then we need to take out elements that require ECPs.

**Comment by Madu86** [comment]
@agoetz I will check all basis sets today. We should remove elements that require ECPs from def2 basis sets and throw appropriate errors if users try to use them.
