### ISSUE TITLE
QUICK doesn't read user specified SCF cycles anymore 

### ISSUE THREAD

**Issue by Madu86** [merzlab/QUICK#142]
@agoetz @Altaimorin The following doesn't work anymore. 

 @ Read Job And Atom

```
  KEYWORD= DFT LIBXC=GGA_X_B88,GGA_C_LYP BASIS=6-31G DIPOLE CUTOFF=1.0D-10 DENSERMS=1.0D-6 CHARGE=+1 SCF=1                                                                          

| Error: Error with keyword SCF encountered.

| Error Termination. Task Failed on: Wed Mar 10 09:06:17 2021
```

This must be fixed ASAP.

**Comment by agoetz** [comment]
@Altaimorin you are searching for a space to terminate the value field. This obviously only works when the value to be read is not at the end of the line. My bad, I did not notice that when reading the code and unfortunately the CI tests did not catch this. @Altaimorin Please make the parser robust and try to break it with many, many tests.
