### ISSUE TITLE
Add aliases for several LIBXC functionals

### ISSUE THREAD

**Issue by Madu86** [merzlab/QUICK#154]
We should add aliases for following LIBXC functionals. 

BP86 -> LIBXC= GGA_X_B88, GGA_C_P86
PW91 -> LIBXC= GGA_X_PW91, GGA_C_PW91
OLYP -> LIBXC= GGA_X_OPTX, GGA_C_LYP
O3LYP -> LIBXC= HYB_GGA_XC_O3LYP
PBE -> LIBXC= GGA_X_PBE, GGA_C_PBE
revPBE -> LIBXC= GGA_X_PBE_R, GGA_C_PBE
PBE0 -> LIBXC=HYB_GGA_XC_PBEH

**Comment by agoetz** [comment]
Let's add also

B97 -> GGA_XC_B97_GGA
