### ISSUE TITLE
Warn users that we use Cartesian basis functions

### ISSUE THREAD

**Issue by agoetz** [merzlab/QUICK#158]
We should warn the users that Quick currently uses basis functions in their Cartesian form and does not support spherical harmonic functions.
- Add warning to manual
- Add warning to output
Note that some basis sets should be used in their Cartesian form, e.g. (some/all?) Pople basis sets.

**Comment by Madu86** [comment]
@agoetz We already have a notification about the cartesian basis in the output. I totally forgot about this. 

```
============== JOB CARD =============
 METHOD = DENSITY FUNCTIONAL THEORY
 DENSITY FUNCTIONAL = B3LYP
 DIRECT SCF 
 SAD INITAL GUESS 
 USE DIIS SCF
 PRINT ENERGY EVERY CYCLE
 Z-MATRIX CONSTRUCTION
 DIPOLE
 STANDARD GRID = SG1
 MAX SCF CYCLES =    200
 MAX DIIS CYCLES =   10
 DELTA DENSITY START CYCLE = 1000
 COMPUTATIONAL CUTOFF: 
      TWO-e INTEGRAL   =  0.100E-08
      BASIS SET PRIME  =  0.100E-19
      MATRIX ELEMENTS  =  0.100E-09
      BASIS FUNCTION   =  0.100E-09
 DENSITY MATRIX MAXIMUM RMS FOR CONVERGENCE  =  0.100E-05
 BASIS SET = 6-31G,  TYPE = CARTESIAN
| BASIS FILE = /home/mmanathunga/pr152/basis/6-31G.BAS
```

**Comment by agoetz** [comment]
OK, good. Yes, we need to update the manual.

**Comment by agoetz** [comment]
The QUICK manual and README files are updated. Closing this issue.
