### ISSUE TITLE
Reusing density matrix in geometry optimizations and MD

### ISSUE THREAD

**Issue by Madu86** [merzlab/QUICK#187]
The density matrix is not reused during MD/geometry optimization calculations. This must be fixed.

**Comment by agoetz** [comment]
This has been fixed for geometry optimizations and API with #188 right?

@Madu86 I think you can close this PR. Maybe open a PR to implement writing results like density matrix, perhaps MOs e.g. for visualization purposes or analysis with external programs, gradients etc; and reading density matrix as guess from the checkpoint file. This can then be used to reuse the density matrix in file based interface.

**Comment by Madu86** [comment]
@agoetz Yes. I am closing this PR.
