### ISSUE TITLE
Set default threshold rms value for density matrix convergence to 10-6 

### ISSUE THREAD

**Issue by Madu86** [merzlab/QUICK#190]
I thought we fixed this. But somehow, the threshold rms value for density matrix convergence still remains as 10-4! (https://github.com/merzlab/QUICK/blob/master/src/modules/quick_method_module.f90#L103, https://github.com/merzlab/QUICK/blob/master/src/modules/quick_method_module.f90#L727). This must be fixed.

**Comment by agoetz** [comment]
Yes, I thought this was changed. And tests updated as required.

Why is this labeled as invalid?

**Comment by Madu86** [comment]
@agoetz This is neither a bug nor a new feature. The "invalid" label definition says "This doesn't seem right". So I chose it. :D

**Comment by agoetz** [comment]
Hmm. I looked up here what it is supposed to mean

https://docs.github.com/en/github/managing-your-work-on-github/managing-labels

`invalid`: Indicates that an issue or pull request is no longer relevant

It still seems quite relevant.

**Comment by agoetz** [comment]
I switched it to bug because this does need fixing even if the code works technically.

**Comment by Madu86** [comment]
Ok Andy.
