### ISSUE TITLE
Consistency of library naming in legacy and CMake build systems

### ISSUE THREAD

**Issue by agoetz** [merzlab/QUICK#192]
It looks like currently the library names and install location differs between the legacy build and CMake build. This should be made consistent. E.g. the legacy build creates

`$installdir/lib/$buildtype` directories and uses names `libquick.so`, `libquick-mpi.so`, etc.

while the CMake build uses

`$installdir/lib` with library names `libquick.so`, `libquick_mpi.so` etc.

Module file location also seems to be inconsistent (in subdirectories of `$installdir/include`)

**Comment by agoetz** [comment]
@Madu86 can we close this?

**Comment by Madu86** [comment]
Yes, we can. The issue is not fixed but the legacy build system will retire in near future.
