### ISSUE TITLE
sander md.in examples for QUICK

### ISSUE THREAD

**Issue by tobigithub** [merzlab/QUICK#210]
Hi,
I have installed quick via minconda (AmberTools21) but I am missing any examples
that will finish within a couple of minutes. I went here but there are no examples 
how to use **QUICK** and **sander** in a QM/MM approach 
(https://quick-docs.readthedocs.io/en/21.3.0/hands-on-tutorials.html)

Basically I am left with literally no information whatsoever.
````
(AmberTools21) usernow@V100x8:~/quick$ sander --help

     mdfil: Error unknown flag: --help                                                                                                                   

     usage: sander  [-O|A] -i mdin -o mdout -p prmtop -c inpcrd -r restrt
                   [-ref refc -x mdcrd -v mdvel -e mden -frc mdfrc -idip inpdip -rdip rstdip -mdip mddip
                   -inf mdinfo -radii radii -y inptraj -amd amd.log -scaledMD scaledMD.log] -cph-data -ce-data <file>
Consult the manual for additional options.
(AmberTools21) usernow@V100x8:~/quick$

````

So I wonder if there are any simple example files for the conda installation with sander and QUICK. Maybe an optimization, or an MD calculation over 10 steps, or a simple energy calculation. It would be nice to have them on the github or here (https://quick-docs.readthedocs.io/). Could be copy/paste instead of downloading large protein files. Basically very simple examples for first time users, even smaller than morphine shown here (https://quick-docs.readthedocs.io/en/21.3.0/performance.html#accuracy-of-energies-and-gradients). Maybe molecules 50-120 Dalton.
Thank you!

**Comment by Madu86** [comment]
Hi @tobigithub , 

You can find a few QM/MM MD examples in $AMBERHOME/test/qmmm_Quick/QMMM_MD folder. Have you already checked them? I am not sure if there are other tests. @agoetz @vwcruzeiro Can you please comment? 

> So I wonder if there are any simple example files for the conda installation with sander and QUICK. Maybe an optimizatio, or an MD calculation over 10 steps, or a simple energy calculation. It would be nice to have them on the github or here (https://quick-docs.readthedocs.io/)

Thanks for pointing this out.

**Comment by tobigithub** [comment]
Hi @Madu86,
Are these examples in the QMMM folder?  I only have ambertools installed (v21, v20 shown below).

![image](https://user-images.githubusercontent.com/2569565/135372421-219db53c-3837-4216-9454-a6684a1294f5.png)

I could not find the folder I just want  a simple example like water or benzene MD. I could not find any folder like QMMM_MD_QUICK only QMMM_MD_Q-Chem or QMMM_MD_ADF

**Comment by Madu86** [comment]
hm, I am not why the tests are missing. I have no experience with miniconda based Amber installation. @agoetz @vwcruzeiro Any idea? Usually, there are tests for file based QM/MM in $AMBERHOME/test/qmmm_EXTERN/QMMM_MD_Quick folder. I am attaching them here:
[QMMM_MD_Quick.tar.gz](https://github.com/merzlab/QUICK/files/7256098/QMMM_MD_Quick.tar.gz)

For API version, tests should be located in $AMBERHOME/test/qmmm_Quick folder.
[qmmm_Quick.tar.gz](https://github.com/merzlab/QUICK/files/7256103/qmmm_Quick.tar.gz)

-Madu

**Comment by tobigithub** [comment]
@Madu86 
Thank you!
T
