### ISSUE TITLE
6-31+G(d) not working for Zn atoms

### ISSUE THREAD

**Issue by wg12385** [merzlab/QUICK#241]
I am trying to use Quick to run a QMMM minimisation of a Zinc containing protein. Running the simulation with quick namelist section:
```
&quick
 method   = 'B3LYP',
 basis    = '6-31+G(d)',
 executable = 'quick.cuda',
/
```
Runs fine for a protein without a Zinc atom, but fails with the following error for a protein with zinc atom present:
```
 For Atom Kind =    5
 ELEMENT = ZN
 BASIS FUNCTIONS =    0

| Error: Unable to find basis set information for this atom.
```
This is despite the basis set appearing to have Zn defined (in the amber20/AmberTools/src/quick/basis/6-31GD.BAS file)

If i am making a simple mistake any help would be appreciated, but this appears it may be a bug.

**Comment by agoetz** [comment]
I am closing this issue because this is not an issue with the code but a user mistake. The 6-31+G(d) basis set does not contain functions for Zn.
