### ISSUE TITLE
QUICK compilation fails with DEBUG flag

### ISSUE THREAD

**Issue by Madu86** [merzlab/QUICK#249]
Just noticed that QUICK fails to compile with debug flags when legacy build system is used. The error is coming from dlfind. This should be fixed. @akhilshajan Can you check this? 

> gfortran -o /tmp/manathun/QUICK/bin/quick.cuda /tmp/manathun/QUICK/build/obj/cuda/main/main.o -L/tmp/manathun/QUICK/build/lib/cuda -lquick-cuda -lxc-cuda -ldlfind -ldftd3 -llapack -lblas-quick -lgfortran -L/opt/software/CUDAcore/11.0.2/lib64 -lcuda -lm -lcudart -lcudadevrt -lcublas -lcusolver -O0 -g -DDEBUG -DDEBUGTIME -mtune=native -ffree-form -cpp -DGNU   -I/tmp/manathun/QUICK/build/include/cuda -J/tmp/manathun/QUICK/build/include/cuda -I/tmp/manathun/QUICK/src/util -I/tmp/manathun/QUICK/build/include/common -DCUDA -lstdc++
> /opt/software/binutils/2.34-GCCcore-9.3.0/bin/ld: /tmp/manathun/QUICK/build/lib/cuda/libdlfind.a(dlfind_main_driver.o): in function `dlf_get_gradient_':
> /tmp/manathun/QUICK/src/dlfind/dlfind_main_driver.f90:376: undefined reference to `__quick_exception_module_MOD_raise_exception'
> /opt/software/binutils/2.34-GCCcore-9.3.0/bin/ld: /tmp/manathun/QUICK/src/dlfind/dlfind_main_driver.f90:382: undefined reference to `__quick_exception_module_MOD_raise_exception'
> collect2: error: ld returned 1 exit status

Compilers: GCC/9.3.0, CUDA/11.0.207, OpenMPI/4.0.3

**Comment by akhilshajan** [comment]
I just fixed the bug. It was coming from CHECK_ERROR statement, so I followed same format to define as in util.fh.

**Comment by Madu86** [comment]
Thanks. Please place a PR so that we can review and merge your changes.
