### ISSUE TITLE
How can MOLDEN and NBO files be generated using QUICK?

### ISSUE THREAD

**Issue by jimkress65** [merzlab/QUICK#251]
How can MOLDEN and NBO files be generated using QUICK?

**Comment by Madu86** [comment]
Hi @jimkress65, Thanks for reaching out. Unfortunately, this feature is currently not available in QUICK; but will be added down the line.

**Comment by jimkress65** [comment]
Thank you for the reply.

 

You might want to consider its implementation since the properties calculated by QUICK are few.  With the MOLDEN file, many properties can be calculated using Multiwfn and similar programs.  Also, some QC packages, e.g. ORCA, can use MOLDEN files as data sources for MO interchange.

 

Jim Kress

 

James Kress Ph.D., President

The KressWorks® Institute 

An IRS Approved 501 (c)(3) Charitable, Nonprofit Corporation

“Engineering The Cure” ©

(248) 573-5499

 

Learn More and Donate At:

Website:  <http://www.kressworks.org/> http://www.kressworks.org

 

Confidentiality Notice | This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential or proprietary information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, immediately contact the sender by reply e-mail and destroy all copies of the original message.

**Comment by jimkress65** [comment]
Thank you for the reply.

 

You might want to consider its implementation since the properties calculated by QUICK are few.  With the MOLDEN file, many properties can be calculated using Multiwfn and similar programs.  Also, some QC packages, e.g. ORCA, can use MOLDEN files as data sources for MO interchange.

 

Here’s a link to a MOLDEN file format specification:

 

https://www.theochem.ru.nl/molden/molden_format.html

 

Jim Kress

 

James Kress Ph.D., President

The KressWorks® Institute 

An IRS Approved 501 (c)(3) Charitable, Nonprofit Corporation

“Engineering The Cure” ©

(248) 573-5499

 

Learn More and Donate At:

Website:  <http://www.kressworks.org/> http://www.kressworks.org

 

Confidentiality Notice | This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential or proprietary information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, immediately contact the sender by reply e-mail and destroy all copies of the original message.

**Comment by Madu86** [comment]
Thanks for pointing this out and sharing the link. We will add this feature in next release.

**Comment by jimkress65** [comment]
Glad I could help.  It will make the QUICK/Amber combination much more useful for me and other users.

 

Jim Kress

 

James Kress Ph.D., President

The KressWorks® Institute 

An IRS Approved 501 (c)(3) Charitable, Nonprofit Corporation

“Engineering The Cure” ©

(248) 573-5499

 

Learn More and Donate At:

Website:  <http://www.kressworks.org/> http://www.kressworks.org

 

Confidentiality Notice | This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential or proprietary information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, immediately contact the sender by reply e-mail and destroy all copies of the original message.

**Comment by Madu86** [comment]
Hi @jimkress65, we have implemented this feature and is available in the latest quick master branch. Can you please check? You just have to add `EXPORT=MOLDEN` into your input file. Thanks!
