### ISSUE TITLE
Differences in the HF energies for the cc-pVDZ basis set

### ISSUE THREAD

**Issue by q-posev** [merzlab/QUICK#268]
Hello QUICK,

First of all, thank you for all the hard work you put into this software!

I have been running some Hartree-Fock benchmark calculations for different basis sets and have observed that the HF/cc-pVDZ results for some molecules differ significantly from the reference codes. Below is a brief description of the software stack:
- QUICK running in a container, installed from the latest [release tag 22.03](https://github.com/merzlab/QUICK/releases/tag/QUICK-22.03). In fact, I also tried QUICK build from the latest commit ac19bfe4749dbe83d76b93125e3f7c5afda4beca and with more tight cutoffs for different quantities and I keep getting the same value. I also tried to regenerate the SAD guess and recalculate the HF energy from it, but the result did not change much
- Psi4 (release 1.3.2, Git: Rev {HEAD} ecbda83) 
- GAMESS (release 17.09-r2) [container from the NVIDIA catalog](https://catalog.ngc.nvidia.com/orgs/hpc/containers/gamess)

Compiled and run on x86_64 machines with A100 (cluster) and T550 (laptop) NVIDIA GPUs.

**Note 1:** I used a water molecule geometry different from the one that you have in the unit test [here](https://github.com/merzlab/QUICK/blob/master/test/ene_H2O_rhf_ccpvdz.in).
**Note 2:** results computed with Pople basis sets are in perfect agreement with the reference codes (errors within $10^{-8}$ Hartree).

Below I am reporting the HF/cc-pVDZ energies in Hartree for a water molecule (same geometry has been used for all calculations):

| QUICK   |      Psi4      |  GAMESS |
|----------|:-------------:|------|
| -76.026199736 |  -76.025888236 | -76.025888241 |

**Question:** is it expected to have the mHartree differences for larger basis sets? 

The QUICK input is the following:
```
 HF BASIS=cc-pVDZ cutoff=1.0e-9 denserms=1.0e-8 ENERGY
 
 O  -0.06756756   -0.31531531    0.00000000  
 H   0.89243244   -0.31531531    0.00000000  
 H  -0.38802215    0.58962052    0.00000000  
```

If I use the water molecule geometry from the aforementioned unit test, the results are slightly better but still within $10^{-4}$:

| QUICK   |      Psi4      |  GAMESS |
|----------|:-------------:|------|
| -75.999485993|   -75.999131653 | -75.999131682 |

**Comment by Madu86** [comment]
Hi @q-posev, Thanks for running the tests and sharing your results. It looks like you were using spherical harmonics in psi4 and gamess runs. Can you please rerun them with cartesian basis functions? QUICK currently doesnt support spherical harmonics.

**Comment by q-posev** [comment]
Hi @Madu86, thank you for the prompt reply! 
Indeed, I missed that point in my input files. So the updated Psi4 value (cartesian basis) is `-76.026199751`, which is indeed in a very good agreement with the QUICK result. My bad!
This should be the reason behind some convergence issues, which we observe during the HF/cc-pVDZ calculations for larger molecules.
Feel free to close this issue when needed.

**Comment by Madu86** [comment]
Awesome! Thanks for the confirmation. Closing this issue..
