### ISSUE TITLE
unable to generate shared libraries...

### ISSUE THREAD

**Issue by akashpg1996** [merzlab/QUICK#273]
hi quick,
I am trying to generate shared libraries.
getting  following error during compilation of lapack libraries.
 relocation R_X86_64_PC32 against symbol `dlamc1_' can not be used when making a shared object; recompile with -fPIC

please help.

**Comment by Madu86** [comment]
Hi @akashpg1996, 
According to your error message, lapack wasn't compiled as position independent code. Both Make and CMake build systems are supposed to take care of this without the intervention of user. Can you provide more details? Specifically, 1) QUICK version (git commit ID if possible), 2) build system used, 3) configure commands used for Make/CMake build configuration, 4) compiler toolchains used.

**Comment by akashpg1996** [comment]
Thanks for your reply@Madu86 
the details are 
1) QUICK version = QUICK 22.03
2) build system = Make 
3) configuration commands =./configure --cuda --shared --arch pascal --prefix /home/mani/software/QUICK_install/ gnu
4) compiler toolchains used= file attached 
[make.cuda.in.txt](https://github.com/merzlab/QUICK/files/10132358/make.cuda.in.txt)

One thing I have noticed, maybe its a naive observation, that there is no 'LAPACK_FLAGS'  variable in compiler toolchain.

**Comment by Madu86** [comment]
@akashpg1996 Thanks for pointing this out. I have already placed a PR containing corresponding fix. If you dont want to wait until the patch is released, feel free to make these changes: https://github.com/merzlab/QUICK/commit/a0aa319df4a66cd69878480f8a9bcad40d2939d5 in your local copy of the code.

**Comment by akashpg1996** [comment]
@Madu86 Thanks for fix. I made changes according to a0aa319. still getting same error. Now we have -fPIC in our flags, Its little confusing.

**Comment by Madu86** [comment]
Did you clean up everything (I.e. running “make distclean” or deleting build, bin directories manually) before running configure again? 

With regards,
Madu

**Comment by akashpg1996** [comment]
yes. You are right. running ' make distclean'  and configuring again solved the problem.

Thanks
Akash

**Comment by Madu86** [comment]
Ok. Great!
