### ISSUE TITLE
Problem with specifying number of optimization cycles

### ISSUE THREAD

**Issue by Madu86** [merzlab/QUICK#280]
According to manual OPTIMIZE=N should force QUICK to run geometry optimization for N cycles (https://quick-docs.readthedocs.io/en/latest/user-manual.html#geometry-optimization). But this doesnt seem to work in the latest master. See the attached output. 
[2086.out.zip](https://github.com/merzlab/QUICK/files/10776918/2086.out.zip)

**Comment by agoetz** [comment]
I also don't see the max number of geometry optimization steps printed in the output. We should print that.

**Comment by agoetz** [comment]
I mean it gets printed in the DL-FIND Report section (currently seems to be hard-coded to 100?). But I think we should also print it Quick JOB CARD section.
