### ISSUE TITLE
Sander + quick --> quick.out file usage

### ISSUE THREAD

**Issue by avinashkarkada** [merzlab/QUICK#302]
Hey, 
I used the quick implementation on Amber to run a qmmm simulation. How do I generate the trajectory in pdb format or any other format that cpptraj accepts? (I have the "quick.out" file)

Thank you

**Comment by agoetz** [comment]
When running a QM/MM simulations with Amber, the sander MD code will produce an mdcrd trajectory file. This trajectory file can be processed with cpptraj or other programs like VMD. If you are interested only in the QM region atoms, then you can conveniently use the same atom mask in cpptraj that you have used in the mdin input file for the QM/MM MD simulation to select the QM region. I hope this helps. 

I am going to close this issue as it is not a coding issue. Please do not create an "Issue" for user related questions but rather ask under "Discussions". Thanks.
