### ISSUE TITLE
Support for F functions is disabled during Transition metal Fe or Co

### ISSUE THREAD

**Issue by shakiralisiddiqui** [merzlab/QUICK#372]
KEYWORD=UDFT B3LYP BASIS=DEF2-SVP SCF=9999 DENSERMS=.0000010000 CUTOFF=.0000000100 GRADCUTOFF=.0000001000 BASISCUTOFF=.0000010000 CHARGE=0 MULT=2 GRADIENT EXTCHARGES
 ============== JOB CARD =============
 METHOD = DENSITY FUNCTIONAL THEORY
 USING LIBXC VERSION: 4.3.4
 FUNCTIONAL INFORMATION:
 NAME = B3LYP FAMILY = HYBRID GGA KIND = EXCHANGE CORRELATION
 DIRECT SCF
 SAD INITAL GUESS
 UNRESTRICTED SYSTEM
 USE DIIS SCF
 PRINT ENERGY EVERY CYCLE
 READ SAD GUESS FROM FILE
 EXTERNAL CHARGES
 STANDARD GRID = SG1
 GRADIENT CALCULATION
 MAX SCF CYCLES =   9999
 MAX DIIS CYCLES =   10
 DELTA DENSITY START CYCLE =    3
 COMPUTATIONAL CUTOFF:
      TWO-e INTEGRAL   =  0.100E-07
      BASIS SET PRIME  =  0.100E-08
      MATRIX ELEMENTS  =  0.100E-09
      BASIS FUNCTION   =  0.100E-05
      GRADIENT CUTOFF  =  0.100E-06
 DENSITY MATRIX MAXIMUM RMS FOR CONVERGENCE  =  0.100E-05
 BASIS SET = DEF2-SVP,  TYPE = CARTESIAN
| BASIS FILE = /usr/local/PROGRAMS/amber22/AmberTools/src/quick/basis/DEF2-SVP.BAS

 @ Finish reading job

 @ Begin SAD initial guess

 For Atom Kind =    1
 ELEMENT = S
 BASIS FUNCTIONS =   19
 For Atom Kind =    2
 ELEMENT = N
 BASIS FUNCTIONS =   15
 For Atom Kind =    3
 ELEMENT = C
 BASIS FUNCTIONS =   15
 For Atom Kind =    4
 ELEMENT = H
 BASIS FUNCTIONS =    5
 For Atom Kind =    5
 ELEMENT = FE

**| Error: Support for F functions is disabled. Please recompile the code with support for F functions.

| Error Termination. Task Failed on: Sun Jun  2 22:00:14 2024**

**Comment by agoetz** [comment]
F functions have been enabled in QUICK-24.03 and AmberTools24.

By default QUICK-24.03 either standalone or distributed with AmberTools24 compiles without F function support. If you want to enable F functions, then you have to add `-DENABLEF=TRUE` when running `cmake`. Please note that the GPU code will take a long time to compile.

Note this will not work with older versions of QUICK or AmberTools.
