### ISSUE TITLE
install error: 23.08 with AMD GPU

### ISSUE THREAD

**Issue by c00jsw00** [merzlab/QUICK#377]
Dear all, 
This is an error.  Could U tell me how to overcome it ?
[QUICK]  CC /home/c00jsw00/quick/QUICK-QUICK-23.08-with-patches/build/common/gpu/libxcobj/gpu.o
make[2]: Nothing to be done for 'libxc_device'.
make[2]: Nothing to be done for 'all'.
make[2]: Nothing to be done for 'allbutxc'.
make[2]: Nothing to be done for 'xc'.
make[2]: Nothing to be done for 'all'.
[QUICK]  FC /home/c00jsw00/quick/QUICK-QUICK-23.08-with-patches/build/common/cpu/dlfindobj/dlfind_main_driver.o
make[2]: Nothing to be done for 'all'.
lld: error: duplicate symbol: gpu_work_gga_x(gpu_libxc_info*, double, double, double*, double*, double*, double*, int)
>>> defined in /tmp/gpu_getxc-gfx906-317b1b.o
>>> defined in /tmp/libbc-quick-hip-amdgcn-gfx906-30d34f.a(gpu_getxc-hip-amdgcn-amd-amdhsa--gfx906gpu_getxc.bc)

lld: error: duplicate symbol: gpu_xc_rho2dzeta(int, double, double, double*, double*)
>>> defined in /tmp/gpu_getxc-gfx906-317b1b.o
>>> defined in /tmp/libbc-quick-hip-amdgcn-gfx906-30d34f.a(gpu_getxc-hip-amdgcn-amd-amdhsa--gfx906gpu_getxc.bc)

lld: error: duplicate symbol: gpu_work_gga_c(gpu_libxc_info*, double, double, double*, double*, double*, double*, int)
>>> defined in /tmp/gpu_getxc-gfx906-317b1b.o
>>> defined in /tmp/libbc-quick-hip-amdgcn-gfx906-30d34f.a(gpu_getxc-hip-amdgcn-amd-amdhsa--gfx906gpu_getxc.bc)

**Comment by agoetz** [comment]
We need more information to investigate. Please give us information on your software stack (compiler, ROCm version) and cmake command you are using to try to understand what may be going wrong.

**Comment by c00jsw00** [comment]
Dear Sir,
This is my information:

Operating system: linux
Requested compiler: GNU.
  gfortran version 7.5.0 found..
  gcc version 7.5.0 found..
  g++ version 7.5.0 found..
QUICK will be installed in /home/c00jsw00/bin/quick
A total of 12 cores will be used for the compilation.
HIP version 6.0 detected
F functions will be compiled in the hip version.
Input file for GNU make was successfully created.

Kind regards
YT

Andreas Goetz ***@***.***> 於 2024年7月21日 週日 上午7:26寫道：

**Comment by agoetz** [comment]
Thanks for providing this information. It looks like you are trying to compile code for F functions with QUICK version 23.08.

F functions are not available in QUICK-23.08. Only CUDA code for Nvidia GPUs in QUICK-24.03 supports F functions.

See here for supported features / limitations in QUICK-23.08: https://quick-docs.readthedocs.io/en/23.8.0/features-limitations.html

Can you please share the cmake command that you used? (for example `cmake ../ -DCOMPILER=GNU -DHIP=TRUE -DQUICK_USER_ARCH=gfx90a -DCMAKE_INSTALL_PREFIX=${QUICK_INSTALL} -DHIP_TOOLKIT_ROOT_DIR=${ROCM_PATH} -DMAGMA=TRUE -DMAGMA_ROOT=${MAGMA_PATH}`). Thanks.

**Comment by c00jsw00** [comment]
Dear Sir,
When I used this cmake command and succeed to compile the code (cmake ..
-DCOMPILER=GNU -DMPI=FALSE -DHIP=TRUE -DQUICK_USER_ARCH=gfx906
-DCMAKE_INSTALL_PREFIX=${QUICK_INSTALL} -DHIP_TOOLKIT_ROOT_DIR=${ROCM_PATH}
-DMAGMA=TRUE -DMAGMA_ROOT=${MAGMA_PATH}).
Thanks for your help .
YT

Andreas Goetz ***@***.***> 於 2024年7月22日 週一 上午6:05寫道：

**Comment by agoetz** [comment]
Great. It would be nice to know if the tests are passing on your hardware. For now I am going to close this issue. If the tests are failing, please reopen this issue. Thank you.
