### ISSUE TITLE
Add config file for user

### ISSUE THREAD

**Issue by agoetz** [merzlab/QUICK#38]
We should add a configuration file `quick.rc` in the install directory that the user can source in their shell. Content should be
```
export QUICK_INSTALL=/path/to/QUICK/installation
export QUICK_BASIS=$QUICK_INSTALL/basis
export PATH=$QUICK_INSTALL/bin:$PATH
```

The user can then do
```
source /path/to/QUICK/installation/quick.rc
```

**Comment by Madu86** [comment]
I have added this capability in PR #40. Please check and merge.
