### ISSUE TITLE
configure script is deleting existing libraries

### ISSUE THREAD

**Issue by vwcruzeiro** [merzlab/QUICK#39]
If the Quick libraries are already installed, they are being deleted when the `configure` script is executed. This should not happen. Old libraries should be overwritten only when new ones are installed during `make install` or deleted during an action like `make uninstall`, not by the `configure` script.

**Comment by Madu86** [comment]
@vwcruzeiro I have failed to reproduce this issue. In fact, I am not deleting any install/build directories from the configure script: https://github.com/merzlab/QUICK/blob/master/configure.

**Comment by vwcruzeiro** [comment]
It is probably the symbolic links in $AMBERHOME/lib that are being removed then. Could you please check? Thank you!

**Comment by Madu86** [comment]
I have removed symlink creation from Makefile. Instead, we are moving the libraries into amber/lib. Please check PR #42.

**Comment by Madu86** [comment]
@vwcruzeiro Is this issue resolved?

**Comment by vwcruzeiro** [comment]
Yes, issue is resolved in the current master branch.
