### ISSUE TITLE
MPI tests fail

### ISSUE THREAD

**Issue by merzlab** [merzlab/QUICK#44]
MPI tests are failing on some systems when `make test` is executed. 

Testing cudampi version started on 01/18/2021 at 06:22:30 PM. 

_Running test 1 of 17
RHF energy test: s and p basis functions
grep: ene_psb5_rhf_631g.out: No such file or directory
Total energy: , Reference value: -401.844805589. Failed

Running test 2 of 17
RHF energy test: s, p and d basis functions
grep: ene_psb5_rhf_631gss.out: No such file or directory
Total energy: , Reference value: -402.013890161. Failed_

This is due to the fact that `mpirun` has been hardcoded into runtest script: https://github.com/merzlab/QUICK/blob/master/tools/runtest#L276. The choice of mpi executable and flags should be decided by the user.

**Comment by Madu86** [comment]
PR #46 should fix this issue.
