### ISSUE TITLE
MPI version fails for large test cases 

### ISSUE THREAD

**Issue by merzlab** [merzlab/QUICK#45]
Following seg fault is observed for large examples when using mpi version. The example is Valinomycin gradient calculation at B3LYP/6-31G** level of theory. 

forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
quick.MPI          0000000000B2555D  Unknown               Unknown  Unknown
libpthread-2.17.s  00007FEBF06FF630  Unknown               Unknown  Unknown
quick.MPI          00000000004CA2C8  Unknown               Unknown  Unknown
quick.MPI          00000000004C898C  Unknown               Unknown  Unknown
quick.MPI          000000000041FDA9  Unknown               Unknown  Unknown
quick.MPI          0000000000423FD3  Unknown               Unknown  Unknown
quick.MPI          0000000000405017  Unknown               Unknown  Unknown
quick.MPI          0000000000404E9E  Unknown               Unknown  Unknown
libc-2.17.so       00007FEBF003A555  __libc_start_main     Unknown  Unknown
quick.MPI          0000000000404DA9  Unknown               Unknown  Unknown

Compiler: Intel/2018.0.5, MPI: intelmpi/2018.0.5
System: Centos 7,  3.10.0-1127.18.2.el7.x86_64
CPU: AMD FX(tm)-8350 Eight-Core Processor
Memory: 8 GB
Execution command: mpirun -np 4 quick.MPI

**Comment by Madu86** [comment]
8 GB memory is not enough to carry out a problem with 1620 basis functions on 4 cpu cores. Increase memory or decrease the number of cores.
