### ISSUE TITLE
Warnings from NVIDIA compilers

### ISSUE THREAD

**Issue by merzlab** [merzlab/QUICK#55]
Nvidia fortran and nvc compilers (nvcompilers/2020) throw a lot of "declared but never referenced" warnings during the compilation. These have to be silenced.

**Comment by agoetz** [comment]
I assume by silencing you mean cleaning the code by removing variables that are never used.

**Comment by Madu86** [comment]
@agoetz These are coming from libxc since we use only some parts of the code in CUDA version. We cannot remove them. Adding `-Wno-unused-variable` into C flag list should easily solve this.

**Comment by agoetz** [comment]
Ah, OK. Makes sense. But we should use that flag only for libxc. We don't want unused variables to sneak into our code. Thanks!

**Comment by agoetz** [comment]
@Madu86 was this addressed?

**Comment by Madu86** [comment]
Resolved in legacy build at the time but CMake build doesnt support NVIDIA compilers at the moment. Closing this issue now.
