### ISSUE TITLE
Use Run.tests.amber in GitHub checks

### ISSUE THREAD

**Issue by vwcruzeiro** [merzlab/QUICK#66]
Currently, the tests checked by GitHub only take into consideration energies and forces. By also checking the results of the Run.tests.amber script, a higher degree of check would be introduced.

**Comment by Madu86** [comment]
@vwcruzeiro This requires standalone quick to have `program_error.sh` and `dacdif` scripts. Is it possible to keep them as standalone tools in QUICK_HOME/tools directory? Or are there any other dependencies?

**Comment by vwcruzeiro** [comment]
I think you can copy these files to a folder for GitHub, and then set AMBERHOME to this folder only inside GitHub.
