### ISSUE TITLE
Seg fault in cudampi version

### ISSUE THREAD

**Issue by merzlab** [merzlab/QUICK#69]
The following seg fault is observed on DGXA100 when using more than 2 A100s for the attached example input.

```
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 210243 on node rl-dgxa-d22-u30 exited on signal 11 (Segmentation fault).
```

Compilers: GCC/8.3.1, OpenMPI/4.0.4, CUDA/11

Example: 

DFT B3LYP BASIS=6-31G** cutoff=1.0e-9 denserms=1.0e-8 ncyc=1000 GRADIENT

C       -6.3960615647   1.6375500661  -1.0167390582
C       -5.5976011922   1.9479656072    .3156763742
C       -4.1358423840   1.3888885892    .3061559180
C       -4.0900116402   -.2069339772    .0759908147
C       -5.3005244050   -.5559695927   -.7831189443
C       -5.6408352846    .5560151731  -1.7454174478
C       -2.8203119095   -.7723427440   -.5951161079
C       -3.4405167500   1.9809801074   1.5954932385
C       -1.5722954629   -.0769638917   -.1719253097
O       -2.6953275274  -2.1590273791   -.1697708437
O       -1.8693493295   1.2308626735   -.7751223509
C       -1.3334064307   -.1176307913   1.4101576262
C        -.8881044770   1.2874584739   1.4845316346
C         .3196036852   1.5770567320    .9640605315
O       -4.0360627508   2.4497903759   2.5047989338
O       -1.9504980519   2.1870799707   1.7492357544
C        -.2198636798   -.3744036919   -.8072269875
C         .8361321957    .5392960246   -.0882305557
O       -6.3705650302   -.7461436866    .1814962812
C       -7.5079885256  -1.5312544379    .1764442320
O       -7.7343168261  -2.1872429459   1.1532459677
C       -8.4523249942  -1.4157500320   -.9939259615
C       -5.4161056771  -1.5091023683  -2.0070002809
O       -6.2192571555   -.4454467295  -2.6902950026
O       -5.4267626184   3.3774437107    .3776243498
O       -1.6122441118   4.1801170473    .0343779432
C        -.7940923698   5.2257739597    .2990567126
O        -.3048947277   5.8645765943   -.5895332555
C        -.5432141747   5.4736984394   1.7763873918
C        1.2298580068   2.7852908502   1.0315034732
O        1.9361230485   -.3334212217    .3599506557
C        3.1923971442    .0392867864    .0732007951
O        3.4564612550   1.0474089559   -.5229789642
C        4.1741649865  -1.0074733119    .5409360653
C        5.5923102950   -.5507792057    .2305424754
C        6.6535032780  -1.6276654266    .4267849964
C        6.3531145194  -2.9590427132    .6578478411
C        7.3484376981  -3.9223474323    .5946432758
C        8.6553264573  -3.5577622028    .3262773335
C        8.9721236891  -2.2174054241    .1751067514
C        7.9780880254  -1.2615408527    .2323472017
O        4.0117554647  -1.2781153298   1.9325731679
N        5.9708266751    .6810003374    .8873415746
C        6.1083010659   1.9571429450    .3956141999
O        6.3193157933   2.8803620623   1.1682891449
C        5.8856236342   2.2294771536  -1.0684368500
C        6.1182756121   1.3530945943  -2.1154261935
C        5.5666092653   1.5985926913  -3.3627521786
C        4.8504992902   2.7660991077  -3.5880645167
C        4.7600523715   3.7102511809  -2.5859738609
C        5.2758308332   3.4419993713  -1.3326644938
C       -2.1366949616  -3.0476305872  -1.0300505942
O       -2.1451655154  -2.8533797614  -2.2328870532
C       -1.5033714554  -4.2030087508   -.3691075134
C       -1.4395726939  -4.3266981108   1.0054185593
C        -.7638829811  -5.3989751504   1.5627241997
C        -.1728504183  -6.3468606504    .7427716273
C        -.2555829630  -6.2275386962   -.6353203163
C        -.9155593963  -5.1509643641  -1.1911103638
C        -.2097392796  -1.1547474452   1.8364340368
C       -2.4300502071   -.4562312768   2.4707641203
H       -3.6491742439   1.8683152472   -.5155830220
H       -4.2442039674   -.7298028968    .9946070928
H       -6.1319126304   1.5761651125   1.1739416597
H       -6.4278095287   2.5627462321  -1.5682088644
H       -7.3896383806   1.3053381318   -.7744956635
H       -4.7465705868    .9454137315  -2.2120480815
H       -2.8855554103   -.7190312325  -1.6682581370
H       -1.1756471657   1.8958446516   -.6850815225
H       -1.8481632425   3.6442035335    .8091515684
H        -.3040222781   -.0416779115  -1.8339005061
H         .0915191278  -1.3952921601   -.8028715623
H        1.2665207958   1.1759763221   -.8367612418
H       -7.9447751635  -1.4087835985  -1.9396806789
H       -8.9860724820   -.4736978340   -.9254124624
H       -9.1714803590  -2.2205724001   -.9250166491
H       -5.9696659013  -2.4206608341  -1.8715269767
H       -4.4956987862  -1.6916167197  -2.5341522638
H       -6.1859306778   3.7990292112    .8057985278
H        -.4047348600   4.5302819326   2.2918679722
H       -1.4092253680   5.9590265117   2.2201988007
H         .3171040869   6.0931663404   1.8871608880
H        1.4832824150   3.0343295148   2.0569031127
H         .8689347198   3.6687756404    .5365846962
H        2.1684888568   2.5341563953    .5367744746
H        3.9669613366  -1.8924968836   -.0572581027
H        5.5541772134   -.3516751663   -.8217997298
H        5.3544974548  -3.2557099687    .9038847941
H        7.0989139525  -4.9513958159    .7469287918
H        9.4171939156  -4.3036934271    .2407856159
H        9.9857443995  -1.9177653222    .0023467668
H        8.2254733522   -.2253064772    .1253413078
H        3.1299494847  -1.6337868182   2.1083778803
H        6.0936138326    .6250743708   1.8859547914
H        6.7084379892    .4705180459  -1.9833352247
H        5.6743950704    .8727859493  -4.1412749888
H        4.3798456238   2.9274160428  -4.5335955847
H        4.2563843627   4.6442138650  -2.7660687217
H        5.1747305805   4.1495326330   -.5327311357
H       -1.9015964720  -3.5961881882   1.6316249866
H        -.6959960683  -5.4955297144   2.6284271470
H         .3482320371  -7.1761491687   1.1766068045
H         .1934856075  -6.9647950021  -1.2689411336
H        -.9826070096  -5.0258752831  -2.2518209168
H         .6895305096   -.6503325497   2.1318038533
H         .0408559146  -1.8507203279   1.0570933960
H        -.5497152190  -1.7387966223   2.6730562622
H       -2.6864693812  -1.5071204618   2.3903167090
H       -3.3390142876    .1000510598   2.4688669158
H       -1.9770019524   -.2959025420   3.4410100992

**Comment by Madu86** [comment]
This issue occurs only on platforms with low stack memory. It is due to the high stack memory usage by several arrays used for debugging in the ERI distribution algorithm. This has been fixed in PR #72.
