### ISSUE TITLE
Wrong number of primitive functions in the output

### ISSUE THREAD

**Issue by merzlab** [merzlab/QUICK#74]
The number of primitive functions printed into the output is wrong. For example, for olestra 6-31g (C156H278O19, 2131/4962 contracted/primitive functions), QUICK prints the following.

```
============== BASIS INFOS ==============
 BASIS FUNCTIONS = 2131
 NSHELL = 1081 NPRIM  = 2862
 JSHELL = 1081 JBASIS = 2862
```

  Please fix this.

**Comment by Madu86** [comment]
@Altaimorin Can you please fix this minor issue?

**Comment by Altaimorin** [comment]
Can you show how the number of the primitive functions of C156H278O19/6-31g, 4962 is obtained?
