### ISSUE TITLE
Support for OS X with GNU compiler versions 10, 11

### ISSUE THREAD

**Issue by Madu86** [merzlab/QUICK#86]
Serial and MPI versions of old QUICK were capable of running on OS X. However, this is no longer possible with new build systems. Please check and fix this.

**Comment by agoetz** [comment]
Results for CMake build serial and MPI on macOS 11.4 (Big Sur):

- gcc 9.3.0, openmpi 4.1.1, Serial pass, MPI pass
- gcc 10.3.0, openmpi 4.1.1, Serial pass, MPI FAIL
- gcc 11.1.0, openmpi 4.1.1, Serial pass, MPI FAIL

With gcc 10 and gcc 11 the first two MPI tests pass, the third test (ene_psb3_blyp_631g) segfaults. It might be a gcc issue or something with the MPI DFT code in QUICK.

**Comment by agoetz** [comment]
Both serial and MPI tests pass on macOS 13.2 (Ventura) with gcc 12.2.0.

**Comment by agoetz** [comment]
Results for CMake build serial and MPI on macOS 11.7.3 (Big Sur)
- gcc12.2.0, openmpi 4.1.4, Serial pass, MPI pass
- gcc 11.3.0, openmpi 4.1.4, Serial pass, MPI pass
- gcc 10.4.0, openmpi 4.1.4, Serial pass, MPI pass
Looks like we are good.
