### ISSUE TITLE
Linking errors with CUDA/9.0

### ISSUE THREAD

**Issue by Madu86** [merzlab/QUICK#91]
Following linking errors (related to cuSOLVER) are observed when compiling QUICK with CUDA/9.0 

```
/cm/extra/apps/CUDA/9.0.103_384.59/lib64/libcusolver.so: undefined reference to `GOMP_critical_end'
/cm/extra/apps/CUDA/9.0.103_384.59/lib64/libcusolver.so: undefined reference to `omp_get_thread_num'
/cm/extra/apps/CUDA/9.0.103_384.59/lib64/libcusolver.so: undefined reference to `omp_get_num_threads'
/cm/extra/apps/CUDA/9.0.103_384.59/lib64/libcusolver.so: undefined reference to `GOMP_parallel_start'
/cm/extra/apps/CUDA/9.0.103_384.59/lib64/libcusolver.so: undefined reference to `omp_get_max_threads'
/cm/extra/apps/CUDA/9.0.103_384.59/lib64/libcusolver.so: undefined reference to `GOMP_loop_end_nowait'
/cm/extra/apps/CUDA/9.0.103_384.59/lib64/libcusolver.so: undefined reference to `GOMP_critical_start'
/cm/extra/apps/CUDA/9.0.103_384.59/lib64/libcusolver.so: undefined reference to `GOMP_parallel_end'
/cm/extra/apps/CUDA/9.0.103_384.59/lib64/libcusolver.so: undefined reference to `GOMP_loop_dynamic_next'
/cm/extra/apps/CUDA/9.0.103_384.59/lib64/libcusolver.so: undefined reference to `GOMP_loop_dynamic_start'
collect2: error: ld returned 1 exit status
make[1]: *** [cuda] Error 1
make: *** [cuda] Error 2
```
The reason is that cuSOLVER depends on openmp (https://docs.nvidia.com/cuda/archive/9.0/pdf/CUSOLVER_Library.pdf, page 11).  @agoetz Shall we temporarily disable support for CUDA versions < 10.0?

**Comment by agoetz** [comment]
The compilers support OpenMP. We just need to add the right flag at linking stage if CUDA version < 10.
- for gnu compiler: '-fopenmp'
- for Intel compiler: '-liomp5' (might also require '-L/path/to/MKL' according to cuSolver manual, although I am not sure why)

**Comment by Madu86** [comment]
@Altaimorin Can you also help me with this one? @agoetz has already provided the solution.

**Comment by Altaimorin** [comment]
The OPENMP issue is fixed. However I got another one on ICER HPCC:

![image](https://user-images.githubusercontent.com/31492878/109679741-dd444500-7b49-11eb-9fc5-10a1cfee3597.png)
Therefore I added `cuda_dc_flags` for CUDA version < 10 for volta as well.
