### ISSUE TITLE
Ship LAPACK with QUICK

### ISSUE THREAD

**Issue by agoetz** [merzlab/QUICK#95]
Add LAPACK to QUICK. Should get compiled if the user does not have system LAPACK or MKL installed.

**Comment by agoetz** [comment]
@multiplemonomials added double precision and double complex  LAPACK routines to `sr/lapack`. Both BLAS (`src/blas`) and LAPACK libraries get built by CMake if no system BLAS and LAPACK is available.

@Madu86 Do you want to add this to your configure build system? I will leave this issue open for the moment.

**Comment by multiplemonomials** [comment]
fwiw I just copied the Amber builtin LAPACK, so no idea if it has the correct things.

**Comment by Madu86** [comment]
@agoetz Yes, I can add it. Let me first finish issues that I am currently working on.

**Comment by agoetz** [comment]
It has all we need and more. It does not contain functions for single precision and complex data types but we do not need those. What we could do is actually remove functions that we are not using. At the very least we could remove the double complex functions. LAPACK (and BLAS) naming convention is starting letter of function s = single precision, d = double precision, c = complex, z = double complex.

**Comment by agoetz** [comment]
LAPACK (subset of functions used in QUICK or AMBER) was added. Works with CMake. Needs to be added to configure based build.

**Comment by agoetz** [comment]
@Madu86 this looks like it is resolved. Can we close this issue?

**Comment by Madu86** [comment]
Yes!
