### ISSUE TITLE
MP2 test hanging, should not run for MPI or CUDA-MPI

### ISSUE THREAD

**Issue by agoetz** [merzlab/QUICK#97]
Test 10 is hanging on Expanse. This is an MP2 test. SERIAL and CUDA works. But the test is also executed for MPI and CUDA-MPI and these are (or seem) not functional. Should disable this MP2 test for those targets.

**Comment by Madu86** [comment]
@agoetz @Altaimorin I have never looked at MP2, particularly this subroutine: https://github.com/merzlab/QUICK/blob/master/src/calMP2.f90#L252-L555. My wild guess is some race is going on here: https://github.com/merzlab/QUICK/blob/master/src/calMP2.f90#L471-L500. This should be fixed using reduce operations (see for eg. https://github.com/merzlab/QUICK/blob/master/src/scf_operator.f90#L211-L224). Probably it is a good idea to run mp2 only on master compute rank (https://github.com/merzlab/QUICK/blob/master/src/main.f90#L246-L251) until this is investigated.

**Comment by agoetz** [comment]
The test script is currently set up to run MP2 tests for `quick.MPI` and `quick.cuda.MPI` without mpirun, i.e. in serial. This leads to hanging jobs. I am not sure why but that's besides the point: If we do not have a working MPI or cuda.MPI implementation of MP2, then we should skip those tests for MPI until we have a working version.

**Comment by agoetz** [comment]
No need to change the MP2 code. PR #101 fixes this issue, which had to do with wrong call to MPI codes by the test runscript.

**Comment by agoetz** [comment]
Closing this issue as it was addressed in PR #108.
