### ISSUE TITLE
Test opt_wat_rhf_ccpvdz executable quick.cuda.MPI fails with Intel, OpenMPI

### ISSUE THREAD

**Issue by agoetz** [merzlab/QUICK#98]
Hard-/software stack
- chinotto
- Intel Parallel Studio XE 2020
- OpenMPI 4.0.5 (compiled with gnu 4.8.5)
- CUDA 11.0

Revision c0cd59061 (PR #96)

Configuration
`./configure --serial --mpi --cuda --cudampi --arch turing --prefix install_intel-19.1_openmpi-4.0.5_c0cd5906 intel`

Test 18 fails for CUDA-MPI
```
[agoetz@chinotto foo]$ mpirun -np 2 quick.cuda.MPI opt_wat_rhf_ccpvdz.in
quick.cuda.MPI: /scratch/agoetz/QUICK/src/cuda/cusolver/quick_cusolver.c:165: cuda_diag_: Assertion `CUSOLVER_STATUS_SUCCESS == cusolver_status' failed.
quick.cuda.MPI: /scratch/agoetz/QUICK/src/cuda/cusolver/quick_cusolver.c:165: cuda_diag_: Assertion `CUSOLVER_STATUS_SUCCESS == cusolver_status' failed.
forrtl: error (76): Abort trap signal
Image              PC                Routine            Line        Source             
quick.cuda.MPI     0000000000A19AFB  Unknown               Unknown  Unknown
libpthread-2.17.s  00007FD58D90F630  Unknown               Unknown  Unknown
libc-2.17.so       00007FD58D568387  gsignal               Unknown  Unknown
libc-2.17.so       00007FD58D569A78  abort                 Unknown  Unknown
libc-2.17.so       00007FD58D5611A6  Unknown               Unknown  Unknown
libc-2.17.so       00007FD58D561252  Unknown               Unknown  Unknown
quick.cuda.MPI     00000000005F6176  Unknown               Unknown  Unknown
quick.cuda.MPI     00000000004C91F6  Unknown               Unknown  Unknown
quick.cuda.MPI     0000000000427667  Unknown               Unknown  Unknown
quick.cuda.MPI     00000000004A54BF  Unknown               Unknown  Unknown
quick.cuda.MPI     000000000040D18C  Unknown               Unknown  Unknown
quick.cuda.MPI     000000000040CCB2  Unknown               Unknown  Unknown
libc-2.17.so       00007FD58D554555  __libc_start_main     Unknown  Unknown
quick.cuda.MPI     000000000040CBB2  Unknown               Unknown  Unknown
forrtl: error (76): Abort trap signal
Image              PC                Routine            Line        Source             
quick.cuda.MPI     0000000000A19AFB  Unknown               Unknown  Unknown
libpthread-2.17.s  00007F09C9C90630  Unknown               Unknown  Unknown
libc-2.17.so       00007F09C98E9387  gsignal               Unknown  Unknown
libc-2.17.so       00007F09C98EAA78  abort                 Unknown  Unknown
libc-2.17.so       00007F09C98E21A6  Unknown               Unknown  Unknown
libc-2.17.so       00007F09C98E2252  Unknown               Unknown  Unknown
quick.cuda.MPI     00000000005F6176  Unknown               Unknown  Unknown
quick.cuda.MPI     00000000004E74F7  Unknown               Unknown  Unknown
quick.cuda.MPI     00000000004E2DBD  Unknown               Unknown  Unknown
quick.cuda.MPI     0000000000427769  Unknown               Unknown  Unknown
quick.cuda.MPI     00000000004A54BF  Unknown               Unknown  Unknown
quick.cuda.MPI     000000000040D18C  Unknown               Unknown  Unknown
quick.cuda.MPI     000000000040CCB2  Unknown               Unknown  Unknown
libc-2.17.so       00007F09C98D5555  __libc_start_main     Unknown  Unknown
quick.cuda.MPI     000000000040CBB2  Unknown               Unknown  Unknown
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 0 on node chinotto exited on signal 6 (Aborted).
--------------------------------------------------------------------------
```

[opt_wat_rhf_ccpvdz.out.txt](https://github.com/merzlab/QUICK/files/6056622/opt_wat_rhf_ccpvdz.out.txt)

**Comment by agoetz** [comment]
This compiler combination works with Jamie's CMake build, revision 0e309f4a.

**Comment by Madu86** [comment]
@agoetz This doesn't make sense. No matter what build system we use, cuSOLVER .so linking only requires two dependent libraries (libblas.so and libblasLt.so) for CUDA 11.0. The error says that quick fails to create cusolver handle  here: https://github.com/merzlab/QUICK/blob/master/src/cuda/cusolver/quick_cusolver.c#L165. Probably there is a bloody memory leak. On v100 (32 GB) the calculation runs fine but I can see that QUICK uses ~12GB (https://pastebin.com/fjvNUTJR), which doesn't make any sense for an example of this size. The same calculation on Titan V eats up the same amount of memory (https://pastebin.com/dEkwpPui) and immediately crashes.

**Comment by agoetz** [comment]
Not sure what is going on. But if you look at the output file (linked at the bottom of my first comment / issue), it happens only in the second geometry optimization step.

**Comment by Madu86** [comment]
The same happens with GNU/8.2.1 and CUDA/10.2 for ene_psb3_b3lyp_631g.in  example. 

```
bin/quick.cuda ene_psb3_b3lyp_631g.in 
quick.cuda: ../src/cuda/cusolver/quick_cusolver.c:165: cuda_diag_: Assertion `CUSOLVER_STATUS_SUCCESS == cusolver_status' failed.
Program received signal SIGABRT: Process abort signal.
Backtrace for this error:
#0  0x14554e49515a
#1  0x14554e4942d3
#2  0x14554d90e9bf
#3  0x14554d90e93f
#4  0x14554d8f8c94
#5  0x14554d8f8b68
#6  0x14554d906df5
#7  0x14554e95d97a
#8  0x14554e9b87e2
#9  0x14554e9bb7ef
#10  0x14554e9a1bcb
#11  0x4024a3
#12  0x401dfc
#13  0x14554d8fa812
#14  0x401e3d
#15  0xffffffffffffffff
Aborted (core dumped)
```

**Comment by Madu86** [comment]
@agoetz So I put a case statement here: https://github.com/merzlab/QUICK/blob/master/src/cuda/cusolver/quick_cusolver.c#L164 and printed what type of `cusolverStatus_t` we are getting when the calculation crashes. I find the following.

```
../bin/quick.cuda wat.in 
CUSOLVER_STATUS_SUCCESS 
CUSOLVER_STATUS_SUCCESS 
CUSOLVER_STATUS_SUCCESS 
CUSOLVER_STATUS_SUCCESS 
CUSOLVER_STATUS_SUCCESS 
CUSOLVER_STATUS_SUCCESS 
CUSOLVER_STATUS_SUCCESS 
CUSOLVER_STATUS_SUCCESS 
CUSOLVER_STATUS_SUCCESS 
CUSOLVER_STATUS_SUCCESS 
CUSOLVER_STATUS_INTERNAL_ERROR 
quick.cuda: /server-home1/madu/Work/Qk/bugfix98/intel/src/cuda/cusolver/quick_cusolver.c:192: cuda_diag_: Assertion `CUSOLVER_STATUS_SUCCESS == cusolver_status' failed.
```
According to the manual (see here: https://docs.nvidia.com/cuda/cusolver/index.html#cuSolverSPstatus) this could mean the following. 

> An internal cuSolver operation failed. This error is usually caused by a cudaMemcpyAsync() failure.
> 
> To correct: check that the hardware, an appropriate version of the driver, and the cuSolver library are correctly installed. Also, check that the memory passed as a parameter to the routine is not being deallocated prior to the routine’s completion.

Perhaps we have a hardware/driver issue on Chinotto? Because this is the only platform I was able to reproduce this issue (tested on PGI and MSU clusters with GCC/4.8.5 and CUDA/11.0.2). Furthermore, I never had this issue when we had CUDA/10.2 installed and I am pretty sure we didn't make any changes to cuSOLVER implementation recently.

**Comment by Madu86** [comment]
> The same happens with GNU/8.2.1 and CUDA/10.2 for ene_psb3_b3lyp_631g.in example.

@vwcruzeiro Please confirm if you were able to run the tests successfully on Delorean.

**Comment by Madu86** [comment]
> This compiler combination works with Jamie's CMake build, revision [0e309f4](https://github.com/merzlab/QUICK/commit/0e309f4a14c6022bb34de59e90b8953d36f52a09).

@agoetz This gives the same problem as you would get from make built executable. I just tested.

**Comment by Madu86** [comment]
@agoetz @vwcruzeiro Ok, the problem is in CUDA/11.0 installation on Chinotto. If you use CUDA/10.2 (`export CUDA_HOME="/usr/local/cuda-10.2"`) and compile the code with same compilers, this problem will disappear.

**Comment by agoetz** [comment]
This has been resolved.
